-- Apply in Supabase SQL Editor before running this app version.
begin;
-- Accept an empty table created manually in Table Editor without dropping it.
-- Existing records with an unknown structure need explicit mapping, not deletion.
do $$
begin
  if to_regclass('public.shift_sessions') is not null and (
    select count(*) < 4 from information_schema.columns
    where table_schema = 'public' and table_name = 'shift_sessions'
      and column_name in ('id', 'user_id', 'data', 'updated_at')
  ) then
    if exists (select 1 from public.shift_sessions limit 1) then
      raise exception 'shift_sessions berisi data dengan struktur lama. Data tidak diubah; petakan kolom lama sebelum melanjutkan migrasi.';
    end if;
    alter table public.shift_sessions alter column id drop identity if exists;
    alter table public.shift_sessions alter column id drop default;
    alter table public.shift_sessions alter column id type text using id::text;
    alter table public.shift_sessions
      add column if not exists user_id uuid not null default auth.uid() references auth.users(id),
      add column if not exists data jsonb not null,
      add column if not exists updated_at timestamptz not null default now();
  end if;
end;
$$;
create table if not exists public.shift_sessions (
  id text primary key,
  user_id uuid not null default auth.uid() references auth.users(id),
  data jsonb not null check (jsonb_typeof(data) = 'object'),
  updated_at timestamptz not null default now(),
  check (data->>'id' = id),
  check (data->>'status' in ('Berjalan', 'Selesai'))
);
create index if not exists shift_sessions_user_idx on public.shift_sessions(user_id);
create unique index if not exists one_active_shift_per_user on public.shift_sessions(user_id)
  where data->>'status' = 'Berjalan';
alter table public.shift_sessions enable row level security;
drop policy if exists "Read own shifts" on public.shift_sessions;
create policy "Read own shifts" on public.shift_sessions for select to authenticated using (user_id = auth.uid());
drop policy if exists "Create own shifts" on public.shift_sessions;
create policy "Create own shifts" on public.shift_sessions for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "Update own shifts" on public.shift_sessions;
create policy "Update own shifts" on public.shift_sessions for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
grant select, insert, update on public.shift_sessions to authenticated;

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id),
  data jsonb not null check (jsonb_typeof(data) = 'object')
);
alter table public.user_profiles enable row level security;
drop policy if exists "Read own profile" on public.user_profiles;
create policy "Read own profile" on public.user_profiles for select to authenticated using (user_id = auth.uid());
drop policy if exists "Create own profile" on public.user_profiles;
create policy "Create own profile" on public.user_profiles for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "Update own profile" on public.user_profiles;
create policy "Update own profile" on public.user_profiles for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
grant select, insert, update on public.user_profiles to authenticated;

create table if not exists public.transactions (
  id text primary key, cashier text not null, created_at timestamptz not null,
  item_count integer not null, subtotal numeric not null, tax numeric not null,
  grand_total numeric not null, paid numeric not null, change numeric not null,
  payment_method text not null, status text not null
);
create table if not exists public.transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id text not null references public.transactions(id) on delete cascade,
  product_id bigint not null, name text not null, price numeric not null,
  quantity integer not null, total numeric not null, note text
);
alter table public.transactions add column if not exists shift_id text;
alter table public.transaction_items add column if not exists note text;
create index if not exists transactions_shift_idx on public.transactions(shift_id);
-- Preserve the existing shared POS ledger access for signed-in staff.
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;
drop policy if exists "POS read transactions" on public.transactions;
create policy "POS read transactions" on public.transactions for select to authenticated using (true);
drop policy if exists "POS insert transactions" on public.transactions;
create policy "POS insert transactions" on public.transactions for insert to authenticated with check (true);
drop policy if exists "POS read items" on public.transaction_items;
create policy "POS read items" on public.transaction_items for select to authenticated using (true);
drop policy if exists "POS insert items" on public.transaction_items;
create policy "POS insert items" on public.transaction_items for insert to authenticated with check (true);
grant select, insert on public.transactions, public.transaction_items to authenticated;
do $$
declare item_sequence text;
begin
  item_sequence := pg_get_serial_sequence('public.transaction_items', 'id');
  if item_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', item_sequence);
  end if;
end;
$$;

-- Header and items commit together. Retrying the same receipt ID never charges/counts twice.
create or replace function public.save_pos_transaction(receipt jsonb)
returns void language plpgsql security invoker set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'Login diperlukan'; end if;
  if jsonb_typeof(receipt->'items') <> 'array' or jsonb_array_length(receipt->'items') = 0
    or receipt->>'status' <> 'Lunas' or (receipt->>'grandTotal')::numeric < 0 then
    raise exception 'Transaksi tidak valid';
  end if;
  insert into public.transactions(id, cashier, created_at, item_count, subtotal, tax, grand_total, paid, change, payment_method, status, shift_id)
  values (receipt->>'id', receipt->>'cashier', (receipt->>'createdAt')::timestamptz,
    (receipt->>'itemCount')::integer, (receipt->>'subtotal')::numeric, (receipt->>'tax')::numeric,
    (receipt->>'grandTotal')::numeric, (receipt->>'paid')::numeric, (receipt->>'change')::numeric,
    receipt->>'paymentMethod', 'Lunas', receipt->>'shiftId')
  on conflict (id) do nothing;
  if not found then return; end if;
  insert into public.transaction_items(transaction_id, product_id, name, price, quantity, total, note)
  select receipt->>'id', (item->>'productId')::bigint, item->>'name', (item->>'price')::numeric,
    (item->>'quantity')::integer, (item->>'total')::numeric, item->>'note'
  from jsonb_array_elements(receipt->'items') item;
end;
$$;
revoke all on function public.save_pos_transaction(jsonb) from public, anon;
grant execute on function public.save_pos_transaction(jsonb) to authenticated;
-- Refresh the API schema after this transaction commits.
notify pgrst, 'reload schema';
commit;
